### ISSUE TITLE
old lvms cannot be removed which breaks ansible task

### ISSUE THREAD

**Issue by gaolitao** [Wind-River/meta-akraino#63]
**Found in build of akraino-image-rec-intel-x86-64-20200219151210.iso**

It seems that there are old lvm mounted to the system which prevented old_vol_rm.sh from remove these old lvms, 
Not sure why this did not happen before, since I have installed several times, need to check if this is a regression issue.

```
TASK [partfs_rootdisk : Delete old LVMs if not mounted already] ****************
Thursday 20 February 2020  00:22:57 -0500 (0:00:00.524)       0:00:37.579 *****
fatal: [controller-1]: FAILED! => {"changed": true, "failed": true, "msg": "non-zero return code", "rc": 5, "stderr": "Shared connection to 172.20.1.154 closed.\r\n", "stdout": "", "stdout_lines": []}
```

- Workaround

```
umount /run/media/dm-6
umount /run/media/dm-0
umount /run/media/dm-1
umount /run/media/dm-2
umount /run/media/dm-4
umount /run/media/dm-5
umount /run/media/dm-3
```

**Comment by jackiehjm** [comment]
I guess it might be caused by “cloud-init”, I fixed several issues for cloud-init,
so it will work correctly but it may try to mount many medias, before that
cloud-init didn’t work, so these medias are not mounted, so they can be removed.

Please investigate if my guess is right, if so, I think the solution is to disable cloud-init on 
controller-1, and it should only be enabled on other controllers deployed by ironic.
